/**
 * CR and VAT validation — DECOUPLED, provisional BFF contracts (to confirm against the
 * middleware spec).
 *
 * CR and VAT are validated independently because they can belong to different
 * organizational levels (e.g. a branch CR under a parent's group VAT). A 1-to-1
 * cross-match in a single request would falsely reject valid onboarding, so each has
 * its own endpoint, its own loading state, and its own server-generated UUID anchor:
 *
 *   POST /api/v1/onboarding/validate-cr   → CrValidationRequest  → CrValidationResponse
 *   POST /api/v1/onboarding/validate-vat  → VatValidationRequest → VatValidationResponse
 */

/** Outcome of validating a single registration. */
export type ValidationOutcome = 'valid' | 'invalid' | 'not_found'

// ── Commercial Registration ─────────────────────────────────────────────────
export interface CrValidationRequest {
  /** KSA CR is 10 digits — not enforced at type level. */
  crNumber: string
}

export interface CrValidationResponse {
  /** Technical UUID v4 generated by the BFF — anchors this CR result to its form card. */
  id: string
  crNumber: string
  businessName?: string
  status: ValidationOutcome
  /** Free-text verification details (reason, registration state, etc.). */
  details?: string
  /** Verification timestamp (ISO-8601). */
  verifiedAt: string
}

// ── VAT Registration ────────────────────────────────────────────────────────
export interface VatValidationRequest {
  /** KSA VAT is 15 digits — not enforced at type level. */
  vatNumber: string
}

export interface VatValidationResponse {
  /** Technical UUID v4 generated by the BFF — anchors this VAT result to its form card. */
  id: string
  vatNumber: string
  businessName?: string
  status: ValidationOutcome
  /** Free-text verification details (reason, registration state, etc.). */
  details?: string
  /** Verification timestamp (ISO-8601). */
  verifiedAt: string
}
