/**
 * WATHQ commercial-registry lookup — provisional BFF contract (to confirm against the
 * middleware spec). The client calls the BFF only; the middleware fronts WATHQ.
 *
 * These are the raw wire shapes. The UI maps failures to `UiError` for display.
 */

/** Commercial registration status as reported by WATHQ. */
export type EntityStatus = 'active' | 'suspended' | 'cancelled' | 'expired' | 'unknown'

export interface AuthorizedRepresentative {
  name: string
  /** National ID / Iqama, when the service scope returns it. */
  nationalId?: string
  role?: string
}

export interface WathqEntity {
  /** Commercial Registration number (KSA CR is 10 digits — not enforced at type level). */
  crNumber: string
  businessName: string
  businessNameAr?: string
  status: EntityStatus
  /** ISO-8601 dates. */
  issueDate?: string
  expiryDate?: string
  registrationType?: string
  /** Subject to service scope per the integration update. */
  authorizedRepresentatives?: AuthorizedRepresentative[]
}

export interface WathqLookupRequest {
  crNumber: string
}

export type WathqLookupStatus = 'found' | 'not_found' | 'error'

export interface WathqLookupResponse {
  /** Technical UUID v4 generated by the BFF — stable anchor for concurrent lookups
   *  (e.g. several branch CRs in a wizard), so each result maps to its own form card. */
  id: string
  status: WathqLookupStatus
  entity?: WathqEntity
  /** Verification timestamp (ISO-8601). */
  retrievedAt: string
}
